---
language: go

go:
  - '1.13.7'

env:
  global:
    - GOOS=linux
    - GOARCH=amd64

before_install:
  - npm install -g snyk
  - snyk auth "${SNYK_API_TOKEN}"

install:
  - go get -v -d -t ./...

script:
  - go test -v -race -cover ./...
  - go build -v -a -o sabercat ./cmd/sabercat
  - snyk test --org=about-source --file=go.mod

before_deploy:
  - sha256sum sabercat | cut -d ' ' -f 1 > sabercat.sha256
  - snyk monitor --org=about-source --file=go.mod

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -T '{sabercat,sabercat.sha256}' -u "${ARTIFACT_USER}:${ARTIFACT_PASS}" "https://artifacts.extern.campact.de/ext/sabercat/${TRAVIS_TAG}/"
    on:
      tags: true
