
---
sudo: required
dist: trusty
language: go

go:
  - 1.9.1

services:
  - docker

env:
  global:
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=1
    - DOCKER_IMAGE=quay.io/campact/sabercat
  matrix:
    - CC=gcc CXX=gcc UPLOAD_ENABLED=1
    - CC=musl-gcc CXX=musl-gcc DOCKER_ENABLED=1

before_install:
  - test $CC != musl-gcc || sudo apt-get install musl-tools

install:
  - go get -v -d -t ./...

script:
  - go test -v -race -cover ./...
  - go build -v -a -o sabercat ./cmd/sabercat
  - test ! $DOCKER_ENABLED || docker build -t $DOCKER_IMAGE .

before_deploy:
  - if [[ $DOCKER_ENABLED ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io;
      test -z $TRAVIS_TAG || docker tag $DOCKER_IMAGE ${DOCKER_IMAGE}:${TRAVIS_TAG};
      test $TRAVIS_BRANCH != "master" || docker tag $DOCKER_IMAGE ${DOCKER_IMAGE}:latest;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push ${DOCKER_IMAGE}:${TRAVIS_TAG};
    on:
      tags: true
      condition: $DOCKER_ENABLED

  - provider: script
    skip_cleanup: true
    script: docker push ${DOCKER_IMAGE}:latest;
    on:
      branch: master
      condition: $DOCKER_ENABLED

  - provider: script
    skip_cleanup: true
    script: curl -T sabercat -u ${ARTIFACT_USER}:${ARTIFACT_PASS} https://artifacts.extern.campact.de/ext/sabercat/${TRAVIS_TAG}/sabercat;
    on:
      tags: true
      condition: $UPLOAD_ENABLED
